spring:
  application:
    name: hyf_shop
  datasource:
    url: jdbc:postgresql://localhost:5432/hyfshop
    username: YOUR_USER_NAME
    password: YOUR_PASSWORD

  sql:
    init:
      # runs schema.sql automatically every time the app starts
      mode: always
server:
  port: '8080'

b2:
  endpoint: https://s3.us-west-004.backblazeb2.com
  region: us-west-004
  access-key: YOUR_KEY_ID
  secret-key: YOUR_APPLICATION_KEY
  bucket: YOUR_BUCKET_NAME